name: Check
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: I pnpm
        run: npm i -g pnpm
      - name: I deps
        run: pnpm i
      - name: Lint
        run: pnpm run lint
